- lightning_talks.yml
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> NBDE Lightningtalk

- team_meetings.yml
> rename weekly team call and give a bit more infos on the scope

- team_meetings.yml
> add team meetings

- team_meetings.yml
> add SIG monitoring

- other.yml
> Add Open Hacking Session

- team_meetings.yml
> Add SIG IAM

- team_meetings.yml
> Add SCS Product Board

- lightning_talks.yml
> move timebox lightning talk to in two week

- onetimes.yml
> Add ORT presentation on 2022-07-21

- lightning_talks.yml
> fix title, not sure why I wrote box not block

- lightning_talks.yml
This lighnting talk will give a brief overview about ideas presented at the [FOSS Backstage](https://foss-backstage.de/) and at [The Foundation for Public Code](https://publiccode.net/). Looking forward to foster ideas how we can adapt these techniques in the SCS community.
> Add lightning talk on how to empower a open community

- team_meetings.yml
> add links to minutes on githut as well as etherpads

- onetimes.yml
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> as a community we want discuss about IaaS layout in SCS stacks

- team_meetings.yml
> add etherpad url and github minutes to sig monitoring

- onetimes.yml
> Add overflow slot meeting for container team 2022-08-08.

- onetimes.yml
> Add debugging session for harbor cluster.

- team_meetings.yml
> Add SIG release scheduled for Wednesday, 14:05 CEST

- team_meetings.yml
> Remove linebreaks to avoid hard word wrapping

- onetimes.yml
> Move session on CA handling

- team_meetings.yml
> add etherpad and github minutes to sig community

- team_meetings.yml
While here, remove the matrix channel that was cut'n pasted from SIG IAM.
> adjust to github for the minutes and add etherpad

- team_meetings.yml
> add etherpad and github minutes to Product Board entry

- onetimes.yml
> add hands-on scs session

- onetimes.yml
> Add harbor meeting on 2022-09-06.

- onetimes.yml
> Add next iteration meeting on Open Operations

- team_meetings.yml
> Add weekly slot for WG Open Operations Manifesto

- other.yml
- team_meetings.yml
> Skip German Unity Day

- onetimes.yml
> whoops. wrong indention.

- onetimes.yml
Signed-off-by: Mathias Fechner <fechner@osism.tech>
> Add overflow appointment to discuss about local empheral disks

- onetimes.yml
> Add our Community Hackathon to public calendar

- lightning_talks.yml
> Add lightning talk by @mleberec

- team_meetings.yml
> Cancel community call on 2022-11-10 due to the OSBA meeting

- team_meetings.yml
> no sig standardization in cw 45 due to OSBA event

- team_meetings.yml
>  no ops&iam call in cw 45 due to OSBA event

- team_meetings.yml
> now that we're on CET again, move IaaS back to 10:05

- team_meetings.yml
> Move exception for SIG Standardization to the deep dive slot

- onetimes.yml
> Add deepdive on GXFS and how they can be deployed on SCS

- onetimes.yml
replacing #63 due to me messing up the git history.
@horazont as this conflicts with SIG Community in SCS-Tech please add the location accordingly
Signed-off-by: Ralf Heiringhoff <ralf.heiringhoff@plusserver.com>
> add audit logging kickoff

- team_meetings.yml
Signed-off-by: maxwolfs <mail@maxwolfs.com>
* bi-weekly meeting, alternating with the SIG Community to discuss knowledge and documentation topics.
> Add SIG Documentation to the calendar

- other.yml
- team_meetings.yml
> bump 'until:' for recurring items to 2023-06-30.

- onetimes.yml
- team_meetings.yml
Both Alex and Kurt are unavail on Thu, thus the shift to Wed. No big date poll -- let's see who is available. We'll have a short meeting if participation is low.
> Shift std/cert SIG this week to Wed 11:05.

- onetimes.yml
- team_meetings.yml
This has been discussed in todays Team OPS & IAM meeting.
> move Team OPS & IAM meeting on dec 1st from 11:05 CET to 13:05 CET.

- team_meetings.yml
> as discussed in today's Team OPS & IAM meeting, move SIG IAM to weekly

- onetimes.yml
> Add dial-in to audit logging kickoff.

- team_meetings.yml
discussed in today's OPS & IAM call
> skip sig monitoring on 2022-11-25

- .github/workflows/yaml2ics.yml
- main.yml
- openops.yml
> Add a seperate calendar for OpenOps

- .github/workflows/yaml2ics.yml
> Fix typo in calendar

- onetimes.yml
> Add the proposed hands-on demo session on 2022-12-09

- lightning_talks.yml
> Add lightning talk on GXFS microservices

- onetimes.yml
> schedule k8s on management plane deep dive for next monday

- team_meetings.yml
> Add SIG SCS Market and schedule SIG Community on a monthly recurrence

- .gitignore
> Ignore manually created communitycall.yml and ics files

- archive/2022/onetimes.yml
- team_meetings.yml
> Remove some duplicate calendar entries that should have been archived

- .github/workflows/test-yaml.yml
> Add a dry-run that checks whether calendar files are valid

- team_meetings.yml
Signed-off-by: maxwolfs <mail@maxwolfs.com>
> Fix formatting

- other.yml
Signed-off-by: maxwolfs <mail@maxwolfs.com>
> Add missing time

- archive/2022/team_meetings.yml
- team_meetings.yml
> added to the wrong file, now added to the right file

- archive/2022/team_meetings.yml
> no community call in CW52

- lightning_talks.yml
> Add lightning talk on SCS compliance tool and openstacksrv2ssh

- team_meetings.yml
> make sure the meeting runs until today

- openops.yml
> fix the end-date, it was set to 2022

- openops.yml
> fix location, noticed by @itrich

- team_meetings.yml
discussed with @alexander-diab
> no SIG Market on 2023-01-26, coordinator is PTO

- lightning_talks.yml
2023-02-09 airgapped installations - current status
Signed-off-by: Tim Beermann <beermann@osism.tech>
> Adding lighning talk

- team_meetings.yml
> this week Jan will coordinate SIG Monitoring, as I'm travelling

- onetimes.yml
See https://alasca.cloud/alasca-tech-talk-2/ for further information.
> Add ALASCA Tech Talk no. 2

- lightning_talks.yml
Thank you so much for your time and the great first discussion we had. We're really looking forward to meeting you! :star_struck:
> Add lightning talk by @georglink on CHAOSS

- team_meetings.yml
> skip SIG Market on 9th and 16th of march

- onetimes.yml
- other.yml
for that day skip hacking session
> schedule scs hands on session on March 10th

- communitycall-data.yml
- communitycall.py
Not perfect, but implementing a LRU cache is overengineering at the moment imho ;)
> allow static assignments

- team_meetings.yml
as discussed in last weeks edition of the SCS Market
> stop SIG SCS Market

- team_meetings.yml
This avoids the conflicts with the ALASCA tech talks for the next few months.
Suggested-by: Alexander Diab <diab@osb-alliance.com>
> CHange weeks for SIG std/cert to happen in even weeks.

- team_meetings.yml
discussed with various participants and coordinated with @horazont
> audit logging breakout has been ended.

- team_meetings.yml
@reqa approached me about this
> IAM will not happen this week, due to vacation and other conferences

- onetimes.yml
- team_meetings.yml
happens each and every time. sigh.
> add the except_on to the correct entries

- team_meetings.yml
... as discussed in the SIG and with @FriederikeZelke
> Extend Community SIG to the end of year and make bi-weekly.

- openops.yml
... as discussed with @FriederikeZelke
> Extend OpenOps Meeting 'till the end of the year.

- lightning_talks.yml
as discussed in todays (2023-05-17) Team IaaS call
> schedule lightning talk on OpenStack Image Manager

- onetimes.yml
spotted by @artifical-intelligence
> align starting time with hedgedoc

- team_meetings.yml
Adds the calendar entry for the new SIG Central API MVP
> Add SIG Central API Meetings

- Add Hackathon to Calendar.yml
- onetimes.yml
- team_meetings.yml
> Add Hackathon Dresden

- openops.yml
Also correct time to use the full hour.
> Add first OpenOps meeting with concrete topic.

- team_meetings.yml
See [2023-09-21 Ops Meeting Minutes](https://github.com/SovereignCloudStack/minutes/pull/356).
> New Series with updated timeslot for SIG Monitoring

- team_meetings.yml
proposed by @garloff and discussed in PB on 2023-09-25
> turn PB into fortnightly

- team_meetings.yml
We will approach the content in other ways (individual meetings, Matrix, etc...)
> Cancel container meetings

- communitycall-data.yml
> remove AD from community call rotation

- communitycall-data.yml
> skip community call tomorrow, since most and everyone is travelling

- team_meetings.yml
thanks @fdobrovolny for pinging me about this
> fix, otherwise it is happening on sunday

- archive/2023/team_meetings.yml
People out sick, so let's skip the last week b/f xmas
> Skip SIG Community on Dec 18 2023.

- archive/2023/team_meetings.yml
As [announced in Team Container Matrix room](https://matrix.to/#/!NZpJdPGjAHISXnHUil:matrix.org/$R_HgDJsJcqVy8QRuEjw9H27xVvTyG2kiXWmi5eMLn2A?via=matrix.org&via=regio.chat&via=matrix.kptt.net)
> chore(team meetings): cancel team container call for 2023-12-21

- team_meetings.yml
Discussed with various people, container meeting will be cancelled this week.
> Cancel container meeting 2024-01-18

- archive/2023/team_meetings.yml
- team_meetings.yml
See https://github.com/SovereignCloudStack/calendar/pull/234
> Change SIG Std/Cert to use 2024 HedgeDocs

- teams/iaas/onetimes.yml
See https://github.com/SovereignCloudStack/minutes/blob/main/iaas/20240313.md#classification-of-scs-supported-openstack-components-and-services-josephinesei-markus-hentsch
> Add overflow for this afternoon, as discussed in Team IaaS last week

- teams/iaas/onetimes.yml
Signed-off-by: Sven Kieske <kieske@osism.tech>
> create IaaS Breakout Session for the DNS Standard

- sig_central_api.yml
- teams/sig_central_api/team_meetings.yml
Sorry for the change in `sig_central_api.yml`, my editor did some autoformatting :see_no_evil:
> feat(central-api): SIG Central API overcame MVP status

- teams/sig_standard_cert/team_meetings.yml
as per decision of /sig-standardization/20240829.md#agenda
> Switch SIG Std/Cert to weekly (with many exceptions)

- teams/sig_standard_cert/team_meetings.yml
> a lot of people are not around tomorrow

- onetimes.yml
raised by @mbuechse - thanks!
Link for ALASCA TechTalk: https://alasca.cloud/alasca-tech-talks/
> move to an hour earlier, so that we don't collide with ALASCA TechTalk

- team_meetings.yml
Also add reasons for skipping ...
> Add another execption: No Project Board today.

- onetimes.yml
> add SCS Summit 2025

- other.yml
People like it and it is well visited, so extend it. Reminded by @mbuechse.
> extend until end of year

- onetimes.yml
- team_meetings.yml
> move ProjectBoard on July 7th to 12:05
