other.yml
Using a monthly intervall schedules recurring events for different weekdays. Let's switch to a weekly interval to always have the Lean Coffee and Monthly Onboarding Session in the same day (Monday/Friday).
Fixes #7
=> Switch to weekly interval to schedule the meetings for the same day

team_meetings.yml
Let's reschedule our SIG community to Monday, 11:05 (starting from 2022-09-26) according to the votes recorded in the corresponding poll.
This conflicts with the Gaia-X Hackathon 5 on the first day, but the following Monday is a public holiday in Germany, so let's stick to 2022-09-26.
Does this work for all of you? @horazont, @tibeer, @ra-beer, @garloff?
=> Reschedule SIG community according to poll

.github/workflows/yaml2ics.yml, requirements.txt
The yaml2ics project released a new version yesterday. Moreover, a dev version of ics has been released and thus requirements can be dropped.
=> Pinpoint version of yaml2ics and ics

onetimes.yml, other.yml, team_meetings.yml
The idea with this is, that we note a coordinator for the meeting to have within the calendar item a contact that can be reached. Furthermore this should reflect a certain ownership of the call, so that it is clear who will prep it.
=> add first round of coordinators to meetings.

team_meetings.yml
As proposed by @garloff, let's skip the meeting today.
=> Cancel today's SIG Standard/Cert deep dive meeting

README.md
We removed the requirements.txt since there is a usable package on pip which can be used. Fix this in the README
=> Remove requirements.txt call from README.MD

team_meetings.yml
Since most of the WG members are in Berlin for a on-site meeting, I propose to postpone the meeting tomorrow.
=> Cancel WG Open Operations on 2022-11-11

team_meetings.yml
All etherpad within our community start with `2022-scs`. Rename the URL of the SIG community accordingly.
=> Streamline url of etherpad for SIG community

onetimes.yml
As discussed with @batistein, we'll postpone the deep dive session on the GXFS microservices to 2023-01-16. Fixes #82
=> Shift GXFS microservices workshop to 2023-01-16

other.yml
There is a SCS Projectteam internal workshop on Dec 12th/13th happening. Due to that there will not be a Lean Coffee.
=> cancel Lean SCS Operator Coffee in CW50

lightning_talks.yml
Due to sickness we have to postpone the scheduled lightning talk on GXFS microservices to January 12th (the week before the deep dive session!)
=> Postpone GXFS lightning talk to January 12th

openops.yml
As discussed during the OpenOps meeting on 2022-12-02, we want to shift the OpenOps meeting to a monthly basis alternating to Lean Operator Coffee with two weeks distance.
=> Shift OpenOps meeting to monthly basis

archive/2022/team_meetings.yml, team_meetings.yml
Discussed and requested by @alexander-diab.
The 2022 entry is moved to the archive file.
=> re-schedule SIG Market to be weekly on thursdays from 11:05 to 11:35.

team_meetings.yml
The chosen timeslot has been proposed by the active members of the SIG IAM (@reqa, @jnull, @matfechner and @JuanPTM).
The board has been created, the pads are ready and the minutes directory will be created, when the first meeting happenend.
=> as discussed, we're splitting the OPS-IAM Team call into two calls.

team_meetings.yml
Some participants require this to be a teams session. We want to be inclusive, so for this meeting we will use teams.
=> switch to teams for audit logging breakout

team_meetings.yml
=> Fix missing time in except_on for fullcalendar.io

team_meetings.yml
it was concluded in today's Team IAM call that :35 is a better starting time than :30
=> move Team IAM to :35

team_meetings.yml
Cancel today's SIG Standardization (due to ALASCA Tech Talk) and shift recurrence by one week, starting from 2023-03-16 as suggested by @fkr.
=> Shift and cancel SIG Standardization

team_meetings.yml
Alex is traveling, Kurt in the IAM workshop, so we lack leadership for 2023-04-13. Let's not just cancel, but rather move by a week.
=> Move SIG std/cert from 2023-04-13 to -04-20.

team_meetings.yml
Product Board 2023-05-22
Team IAM 2023-05-24 (cancelation was ineffective before) SIG IAM 2023-05-19 (OK, not really due to summit)
=> A few more cancelations due to the SCS summit:

onetimes.yml
as discussed in today's IaaS call.
See here: https://input.scs.community/2023-scs-team-iaas#Overflow-Slot-Monday---July-10th
=> add overflow slot for July 10th

team_meetings.yml
This is a draft for the calendar from CW30. For the container team it's largely settled (confirmed by tender winners).
For Team IAM there could be problems at some participants
=> Move container and iam meeting from cw30

other.yml
Since it rarely is filled with people, we dediced to remove it and instead schedule specific sessions when they happen. That way everone knows wether something will really happen.
=> remove open hacking session as discussed in today's product board

team_meetings.yml
Product board today has been canceled.
Since the new cadence should start today we can just skip this.
=> Start new pb cadence on 2023-10-23

onetimes.yml
We will find a new date, but it can't happen today.
=> Cancel the R5 retro on 2023-10-26 for now.

team_meetings.yml
We had 2023 in the file names, so we need new hedgedoc filenames with
2024. Do this for my meetings.
Inside the hedge docs, I also added links to minimize confusion. For reference of old minutes, we of course continue to rely on https://github.com/SovereignCloudStack/minutes/
=> Change Team IAM and ProductBoard to use 2024 hedgedocs.

teams/iaas/onetimes.yml
We need a breakout session regarding the IPv4/6 Networking standardization to discuss further details.
=> Add IaaS IPv4 Breakout session to the calendar

teams/iaas/onetimes.yml
Postpone this by 1 week due to conflict with today's product board meeting.
=> postpone IaaS Breakout Session for the DNS Standard

teams/sig_standard_cert/onetimes.yml
An additional meeting because tomorrow multiple people (myself included) can't attend, and we usually have enough to talk about. I try to avoid the designated overflow slot because it's usually too late in the day for me and my family.
=> schedule SIG Std/Cert on 2024-08-15

teams/sig_central_api/team_meetings.yml
Hi @o-otte, sorry for another PR. Didn't know `until` means `until except`, which resulted in the appointment from today is missing in the calendar now. I just add one more day, which should fix it.
=> fix: end of SIG Central API MVP

teams/sig_standard_cert/team_meetings.yml
too many protagonists will not be available
=> drop 2024-10-17 from SIG Std/Cert schedule: 

teams/iam_n_sec/team_meetings.yml
Please add additional cancelations (e.g. b/c of ALASCA, Reformationstag, Allerheiligen, ...)
=> Remove Team IAM/Sec in cwk 44 (ALASCA summit).

teams/container/team_meetings.yml
The first call will take place on Friday, February 21, 2025, from 09:05 – 09:55 CET,
and will continue on even weeks.
=> Restart Container meeting

teams/sig_standard_cert/team_meetings.yml
As [decided on last meeting](https://github.com/SovereignCloudStack/minutes/blob/main/sig-standardization/20250807.md#next-weeks-meeting)
=> cancel SIG Std/Cert meeting on 2025-08-14
